global using API.Controllers;
global using API.Data;
global using API.Repositories;
global using API.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Newtonsoft.Json;
global using System.Collections.Generic;